config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about'
  resources :books, only: [:create, :edit, :index, :show, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def edit
    @book = Book.find(params[:id])
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book)
  end

  def update
   @book = Book.find(params[:id])
   @book.update(book_params)
   redirect_to book_path(@book.id)
  end

  def destroy
    book =Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>
  <label for="inputtitle">Title</label>
  <%= f.text_field :title, id:"inputtitle"%>
  <label>Opinion</label>
  <%= f.text_field :body%>
  <%= f.submit "Update Book" %>
<% end %>

app/views/books/index.html.erb
<div>
  <h1>Books</h1>
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
            </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <div>
    <p>Title</p>
    <%= f.text_field :title %>
  </div>

  <div>
    <p>Opinion</p>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Book detail</h1>

<table>
  <tr>
    <td>
      <%= link_to user_path(@book.user_id) do %>
        <%= image_tag @book.user.get_profile_image(100,100) %>
      <% end %><br>
      <%= link_to @user.name, user_path(@user) %>
    </td>
    <td>
      <%= link_to book_path(@book.id) do %>
        <%= @book.title %>
      <% end %></td>
    <td>
      <%= @book.body %></td>
  </tr>
</table>
<% if @book.user_id == current_user.id %>
  <td><%= link_to "Edit", edit_book_path(@book)%></td>
  <td><%= link_to "Destroy", book_path(@book), method: :delete%></td>
<% end %>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<h1>welcome to <i class="fa-solid fa-book"></i>Bookers !!</h1>
<p>In <i class="fa-solid fa-book"></i>Bookers,</p>

<p>you can share and exchange your opinions , inpressions , and emotions</p>

<p>about various books!</p>

<p><%= link_to "Log in", new_user_session_path %></p>

<p><%= link_to "Sign up", new_user_registration_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/186a26f36d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <% if user_signed_in? %> <!--ログイン状態なら-->
        <span>
          <%= link_to "Bookers", root_path %>
        </span>
        <span>
          <%= link_to "Home", user_path(current_user.id) %>
        </span>
        <span>
          <%= link_to "Users", users_path %>
        </span>
        <span>
          <%= link_to "Books", books_path %>
        </span>
        <span>
          <%= link_to "Log out",destroy_user_session_path, method: :delete %>
        </span>
      <% else %> <!--ログアウト状態なら-->
        <span>
          <%= link_to "Bookers", root_path %>
        </span>
        <span>
          <%= link_to "Home", root_path %>
        </span>
        <span>
          <%= link_to "About", homes_about_path %>
        </span>
        <span>
          <%= link_to "Sign up", new_user_registration_path %>
        </span>
        <span>
          <%= link_to "Log in", new_user_session_path %>
        </span>
      <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName"%>
  <label>Image</label>
  <%= f.file_field :profile_image, accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, id:"inputIntroduction"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
              <%= image_tag user.get_profile_image(80,80) %>
          </td>
          <td>
              <%= user.name %>
          </td>
          <td>
          <%= link_to "show", user_path(user.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image(80, 80) %>
        <% end %>
        <br>
      </td>
      <td>
        <%= link_to book_path(book) do %>
          <%= book.title %>
        <% end %>
      </td>
      <td>
        <%= book.body %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>